apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Values.configMap.name }}
  namespace: {{ .Values.namespace }}
  labels:
    app: {{ .Values.labels.app }}
    environment: {{ .Values.labels.environment }}
data:
  config_rtmp.toml: |
    [rtmp]
    enabled = true
    port = {{ .Values.configMap.data.rtmp.port }}

    [hls]
    enabled = true
    port = {{ .Values.configMap.data.hls.port }}

    [httpflv]
    enabled = true
    port = {{ .Values.configMap.data.httpflv.port }}

    [log]
    level = "{{ .Values.configMap.data.log.level }}"
