apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.service.name }}
  namespace: {{ .Values.namespace }}
  labels:
    app: {{ .Values.labels.app }}
    environment: {{ .Values.labels.environment }}
spec:
  selector:
    app: {{ .Values.service.selector }}
  ports:
  {{ range .Values.service.ports }}
    - name: {{ .name }}
      port: {{ .port }}
      targetPort: {{ .targetPort }}
  {{ end }}
